# Generated by Django 4.0.5 on 2022-06-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=-1.0, upload_to='images'),
            preserve_default=False,
        ),
    ]
