# Generated by Django 4.0.5 on 2022-06-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_delete_blog_post_category_post_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Cats', max_length=255),
        ),
    ]
